'use client'

import Link from 'next/link'
import { usePathname } from 'next/navigation' // Importing usePathname from next/navigation to get the current path
import Footer from '../components/Footer'

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname()

  const linkStyle = (path: string) =>
    pathname === path
      ? { margin: '0 10px', fontWeight: 'bold', textDecoration: 'underline' }
      : { margin: '0 10px' }

  return (
    <html lang="en">
      <body>
        <nav style={{ padding: '1rem', textAlign: 'center' }}>
          <Link href="/login" style={linkStyle('/login')}>Login</Link>
          <Link href="/register" style={linkStyle('/register')}>Register</Link>
          <Link href="/forgot-password" style={linkStyle('/forgot-password')}>Forgot Password?</Link>
        </nav>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
