// This layout is used for the marketing pages
import Header from './components/Header';
import Footer from './components/Footer';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: {
    default: 'Next.js Najib-Hossain',
    template: '%s | Next.js Najib-Hossain',
    // absolute: '',
  },
  description: 'Generated by Next.js',
}

export default function MarketingLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
